### ISSUE TITLE
Very high CPU usage is due to processor limitations?

### ISSUE THREAD

**Issue by leoauri** [jatinchowdhury18/RTNeural-example#4]
Hi Jatin!

Ableton shows CPU usage of 300-400% when running the compiled example vst on my computer.  
Can you give a reference for CPU usage you experience on what machine?

This is on a 2012 MacBook Pro, whose i5-3210M processor just missed out on FMA support.  Do you know if the backends rely heavily on FMA instructions for the optimisation?

**Comment by jatinchowdhury18** [comment]
Hi Leo,

On my machine (Windows Intel i7-7820HQ), I can run at 25-30% CPU usage (Ableton 10, VST3). I don't believe FMA support should make much difference. Here's a few ideas:

1. Make sure you're building in "release" mode. With CMake this should be `cmake --build build --config Release`. Without release mode, the compiler won't optimize the code fully, especially for SIMD code.

2. Check which RTNeural backend is being used. I was using the "default" backend for this project which is the STL backend, but different backends will give different performance. You may want to pull from the latest `main` branch since I had to adjust the `CMakeLists.txt` a little bit. When you run the CMake configuration step, the output will tell you which backend is being used, so you can double check there. I haven't checked the performance of this plugin with the other backends, but in theory the other backends should have better performance.

Definitely let me know if these suggestions help!

Thanks,
Jatin

**Comment by leoauri** [comment]
Hi Jatin, thanks for writing back!

I am building in Release, essentially the instructions from the README.  Also I noticed from the compiler output that the backend wasn't changing, so I was hard coding it in a deeper `CMakeLists.txt`.  So I can confirm that I get about the same CPU usage on eigen, SIMD and STL backends (SIMD was best but still shows above 300%).  Compiling accelerate failed with some errors.    

Have you compiled the example on mac yourself, or seen it compiled and running?  I will try it on a somewhat newer macbook for comparison asap.  

Can you give a comparison CPU usage on your machine for other vst plugins?  For example Waves Abbey Road plate reverb uses around 38% CPU on my machine.

A funny thing I noticed was that a frozen track would only render audio on one channel through the plugin.

**Comment by leoauri** [comment]
Oh, the AU and standalone versions run fine!  (~50% CPU)  So this only affects the vst build...

**Comment by jatinchowdhury18** [comment]
Okay, good to hear that the AU and Standalone versions work well!

> I noticed from the compiler output that the backend wasn't changing, so I was hard coding it in a deeper CMakeLists.txt.

For some reason, I usually have to do a clean rebuild to get the backend to change correctly. Not exactly sure why... there's probably some CMake trick that I'm not aware of.

> Have you compiled the example on mac yourself, or seen it compiled and running? I will try it on a somewhat newer macbook for comparison asap.

On my Mac machine, both the VST3 and AU builds run at ~30% of my CPU, so the performance is pretty comparable with my other machine, and seems reasonable compared to the 50% CPU on your older Mac. I don't currently have the Waves plugins on my Mac. Is there another plugin you'd like to compare against (maybe a free one, e.g. Valhalla Supermassive on a certain preset)?

I'm guessing the reason the Accelerate builds fail probably has to do with the lack of FMA support that you mentioned earlier.

Would it be possible to run the VST build in Debug mode, and maybe see what's happening differently in that version specifically?

Thanks,
Jatin

**Comment by leoauri** [comment]
Hi Jatin,

1. Valhalla Supermassive doesn't go above 7% CPU on any preset for me.

2. Strangely, the vst3 Release build works now!  Perhaps the JUCE version fixed this and I didn't notice...

Thanks,
Leo
