### ISSUE TITLE
I cant select an input

### ISSUE THREAD

**Issue by creativeguitar** [jatinchowdhury18/RTNeural-example#5]
Repo built successfully. Output works but I get an error after I select an input. 
Any ideas how to fix this ?

![image](https://user-images.githubusercontent.com/19698062/151257394-8d9023d8-4412-4535-805c-7f85155deac2.png)
![image](https://user-images.githubusercontent.com/19698062/151257420-2fd80a4e-ab4a-433b-9187-cf248fb8480e.png)

**Comment by jatinchowdhury18** [comment]
Yeah, running standalone plugins on Windows can be a bit of a pain. The project also builds a VST3 plugin, and I would recommend loading that the plugin into a DAW, so that the DAW can manage the audio devices instead.

Alternatively, it is also possible to build the plugin with ASIO support, but you would need to download the ASIO SDK yourself, since the ASIO license does not allow me to re-distribute the SDK with the rest of the code.

**Comment by creativeguitar** [comment]
Fixed. It was a Windows 10/11 privacy issue

Control panel > Hardware and Sound > Sound: Deactivate all devices that will not be used. For some reason, audio I/O did not work in the presence of other devices (I made sure that the correct devices were selected for I/O so it is not a selection problem).
Settings > Privacy > Microphone: Turn on both “Allow microphone access for this device” and “allow apps to access mic”. This seems to be necessary in order to get access to line inputs, too.
